apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv
  labels:
    type: aws-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: scaws  
  awsElasticBlockStore:
    volumeID: vol-084940dae435ffe02
    fsType: ext4
