apiVersion: v1
kind: PersistentVolume
metadata:
  name: aws-pv
  labels:
    type: aws-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  storageClassName: scaws  
  awsElasticBlockStore:
    volumeID: vol-03e9264e9ead2ad37
    fsType: ext4
